// Copyright (c) Aegis AO Soft LLC and Alexander Orlov. All rights reserved.

namespace HueControl.Services;

/// <summary>
/// All translatable UI strings. Each entry maps a key to translations in the order of
/// <see cref="Loc.Languages"/> (en, es, pt, fr, de, ru, ar, he, zh-Hans, zh-Hant). Placeholders
/// use {0}, {1}, … and are filled with <c>string.Format</c>. Device, room and scene names come
/// from the bridge and are not translated; built-in Hue scene preset names stay in English as
/// they are written to the bridge.
/// </summary>
internal static class Strings
{
    // en, es, pt, fr, de, ru, ar, he, zh-Hans, zh-Hant
    internal static readonly Dictionary<string, string[]> All = new()
    {
        // ── Title bar / flyout ──────────────────────────────────────────────
        ["App_Subtitle"] = new[] { "Philips Hue manager", "Gestor de Philips Hue", "Gestor de Philips Hue", "Gestionnaire Philips Hue", "Philips Hue-Manager", "Менеджер Philips Hue", "مدير Philips Hue", "מנהל Philips Hue", "Philips Hue 管理器", "Philips Hue 管理器" },
        ["Tip_BridgesMenu"] = new[] { "Bridges menu", "Menú de puentes", "Menu de pontes", "Menu des ponts", "Bridge-Menü", "Меню мостов", "قائمة الجسور", "תפריט גשרים", "网桥菜单", "橋接器選單" },
        ["Tip_Settings"] = new[] { "Settings", "Ajustes", "Definições", "Paramètres", "Einstellungen", "Настройки", "الإعدادات", "הגדרות", "设置", "設定" },
        ["Tip_Theme"] = new[] { "Light / dark theme", "Tema claro / oscuro", "Tema claro / escuro", "Thème clair / sombre", "Helles / dunkles Design", "Светлая / тёмная тема", "سمة فاتحة / داكنة", "ערכת נושא בהירה / כהה", "浅色 / 深色主题", "淺色 / 深色主題" },
        ["Tip_Language"] = new[] { "Language", "Idioma", "Idioma", "Langue", "Sprache", "Язык", "اللغة", "שפה", "语言", "語言" },
        ["Tip_Minimize"] = new[] { "Minimize", "Minimizar", "Minimizar", "Réduire", "Minimieren", "Свернуть", "تصغير", "מזעור", "最小化", "最小化" },
        ["Tip_Maximize"] = new[] { "Maximize", "Maximizar", "Maximizar", "Agrandir", "Maximieren", "Развернуть", "تكبير", "הגדלה", "最大化", "最大化" },
        ["Close"] = new[] { "Close", "Cerrar", "Fechar", "Fermer", "Schließen", "Закрыть", "إغلاق", "סגירה", "关闭", "關閉" },
        ["Homes"] = new[] { "HOMES", "HOGARES", "CASAS", "MAISONS", "ZUHAUSE", "ДОМА", "المنازل", "בתים", "住宅", "住家" },
        ["AddHome"] = new[] { "+ Add home", "+ Añadir hogar", "+ Adicionar casa", "+ Ajouter une maison", "+ Zuhause hinzufügen", "+ Добавить дом", "+ إضافة منزل", "+ הוספת בית", "+ 添加住宅", "+ 新增住家" },
        ["AddBridgeBtn"] = new[] { "+ Add bridge", "+ Añadir puente", "+ Adicionar ponte", "+ Ajouter un pont", "+ Bridge hinzufügen", "+ Добавить мост", "+ إضافة جسر", "+ הוספת גשר", "+ 添加网桥", "+ 新增橋接器" },
        ["RemoveSelected"] = new[] { "Remove selected", "Quitar seleccionado", "Remover selecionado", "Retirer la sélection", "Ausgewähltes entfernen", "Удалить выбранное", "إزالة المحدد", "הסרת הנבחר", "移除所选", "移除所選" },
        ["AllOn"] = new[] { "All on", "Todo encendido", "Ligar tudo", "Tout allumer", "Alle ein", "Включить все", "تشغيل الكل", "הכול דולק", "全部开启", "全部開啟" },
        ["AllOff"] = new[] { "All off", "Todo apagado", "Desligar tudo", "Tout éteindre", "Alle aus", "Выключить все", "إيقاف الكل", "הכול כבוי", "全部关闭", "全部關閉" },
        ["Refresh"] = new[] { "Refresh", "Actualizar", "Atualizar", "Actualiser", "Aktualisieren", "Обновить", "تحديث", "רענון", "刷新", "重新整理" },
        ["Rename"] = new[] { "Rename", "Renombrar", "Renomear", "Renommer", "Umbenennen", "Переименовать", "إعادة تسمية", "שינוי שם", "重命名", "重新命名" },
        ["Delete"] = new[] { "Delete", "Eliminar", "Eliminar", "Supprimer", "Löschen", "Удалить", "حذف", "מחיקה", "删除", "刪除" },

        // ── Rooms / Scenes tabs ─────────────────────────────────────────────
        ["Tab_Rooms"] = new[] { "Rooms", "Habitaciones", "Divisões", "Pièces", "Räume", "Комнаты", "الغرف", "חדרים", "房间", "房間" },
        ["Tab_Scenes"] = new[] { "Scenes", "Escenas", "Cenas", "Scènes", "Szenen", "Сцены", "المشاهد", "סצנות", "场景", "場景" },
        ["On"] = new[] { "On", "Encender", "Ligar", "Allumer", "Ein", "Вкл", "تشغيل", "הפעלה", "开", "開" },
        ["Off"] = new[] { "Off", "Apagar", "Desligar", "Éteindre", "Aus", "Выкл", "إيقاف", "כיבוי", "关", "關" },
        ["AddSceneChip"] = new[] { "+ Scene", "+ Escena", "+ Cena", "+ Scène", "+ Szene", "+ Сцена", "+ مشهد", "+ סצנה", "+ 场景", "+ 場景" },
        ["ChooseColour"] = new[] { "Choose colour", "Elegir color", "Escolher cor", "Choisir la couleur", "Farbe wählen", "Выбрать цвет", "اختيار اللون", "בחירת צבע", "选择颜色", "選擇顏色" },
        ["Loading"] = new[] { "Loading…", "Cargando…", "A carregar…", "Chargement…", "Wird geladen…", "Загрузка…", "جارٍ التحميل…", "טוען…", "加载中…", "載入中…" },
        ["DeleteScene"] = new[] { "Delete scene", "Eliminar escena", "Eliminar cena", "Supprimer la scène", "Szene löschen", "Удалить сцену", "حذف المشهد", "מחיקת סצנה", "删除场景", "刪除場景" },

        // ── Add-bridge dialog ───────────────────────────────────────────────
        ["AddBridge_Title"] = new[] { "Add bridge", "Añadir puente", "Adicionar ponte", "Ajouter un pont", "Bridge hinzufügen", "Добавить мост", "إضافة جسر", "הוספת גשר", "添加网桥", "新增橋接器" },
        ["AddBridge_Heading"] = new[] { "Add a Hue bridge", "Añadir un puente Hue", "Adicionar uma ponte Hue", "Ajouter un pont Hue", "Eine Hue-Bridge hinzufügen", "Добавить мост Hue", "إضافة جسر Hue", "הוספת גשר Hue", "添加 Hue 网桥", "新增 Hue 橋接器" },
        ["AddBridge_Sub"] = new[] { "Discover bridges on your network, or type the IP directly.", "Descubre puentes en tu red o escribe la IP directamente.", "Descubra pontes na sua rede ou escreva o IP diretamente.", "Découvrez les ponts sur votre réseau ou saisissez l'IP directement.", "Bridges im Netzwerk suchen oder die IP direkt eingeben.", "Найдите мосты в сети или введите IP вручную.", "اكتشف الجسور على شبكتك، أو أدخل عنوان IP مباشرة.", "גלה גשרים ברשת שלך, או הקלד את כתובת ה-IP ישירות.", "在网络中发现网桥，或直接输入 IP 地址。", "在網路中探索橋接器，或直接輸入 IP 位址。" },
        ["AddBridge_Discover"] = new[] { "Discover on network", "Buscar en la red", "Procurar na rede", "Rechercher sur le réseau", "Im Netzwerk suchen", "Найти в сети", "الاكتشاف على الشبكة", "גילוי ברשת", "在网络中发现", "在網路中探索" },
        ["AddBridge_IpLabel"] = new[] { "Bridge IP address", "Dirección IP del puente", "Endereço IP da ponte", "Adresse IP du pont", "IP-Adresse der Bridge", "IP-адрес моста", "عنوان IP للجسر", "כתובת IP של הגשר", "网桥 IP 地址", "橋接器 IP 位址" },
        ["AddBridge_HomeLabel"] = new[] { "Home (pick or type a new one)", "Hogar (elige o escribe uno nuevo)", "Casa (escolha ou escreva uma nova)", "Maison (choisissez ou saisissez-en une)", "Zuhause (wählen oder neu eingeben)", "Дом (выберите или введите новый)", "المنزل (اختر أو اكتب واحدًا جديدًا)", "בית (בחר או הקלד חדש)", "住宅（选择或输入新的）", "住家（選擇或輸入新的）" },
        ["Cancel"] = new[] { "Cancel", "Cancelar", "Cancelar", "Annuler", "Abbrechen", "Отмена", "إلغاء", "ביטול", "取消", "取消" },
        ["AddBridge_Pair"] = new[] { "Pair (press link button)", "Vincular (pulsa el botón)", "Emparelhar (prima o botão)", "Associer (appuyez sur le bouton)", "Koppeln (Link-Taste drücken)", "Связать (нажмите кнопку)", "إقران (اضغط زر الربط)", "התאמה (לחץ על לחצן הקישור)", "配对（按下连接按钮）", "配對（按下連結按鈕）" },
        ["OK"] = new[] { "OK", "Aceptar", "OK", "OK", "OK", "ОК", "موافق", "אישור", "确定", "確定" },
        ["Add"] = new[] { "Add", "Añadir", "Adicionar", "Ajouter", "Hinzufügen", "Добавить", "إضافة", "הוספה", "添加", "新增" },
        ["ScenePicker_Title"] = new[] { "Add scene", "Añadir escena", "Adicionar cena", "Ajouter une scène", "Szene hinzufügen", "Добавить сцену", "إضافة مشهد", "הוספת סצנה", "添加场景", "新增場景" },
        ["ScenePicker_Sub"] = new[] { "Pick a built-in Hue scene", "Elige una escena Hue integrada", "Escolha uma cena Hue incorporada", "Choisissez une scène Hue intégrée", "Integrierte Hue-Szene wählen", "Выберите встроенную сцену Hue", "اختر مشهد Hue مدمجًا", "בחר סצנת Hue מובנית", "选择内置 Hue 场景", "選擇內建 Hue 場景" },

        // ── Settings window ─────────────────────────────────────────────────
        ["Settings_Header"] = new[] { "Settings — {0}", "Ajustes — {0}", "Definições — {0}", "Paramètres — {0}", "Einstellungen — {0}", "Настройки — {0}", "الإعدادات — {0}", "הגדרות — {0}", "设置 — {0}", "設定 — {0}" },
        ["Save"] = new[] { "Save", "Guardar", "Guardar", "Enregistrer", "Speichern", "Сохранить", "حفظ", "שמירה", "保存", "儲存" },
        ["Set"] = new[] { "Set", "Aplicar", "Definir", "Définir", "Festlegen", "Задать", "تعيين", "הגדרה", "设置", "設定" },
        ["Create"] = new[] { "Create", "Crear", "Criar", "Créer", "Erstellen", "Создать", "إنشاء", "יצירה", "创建", "建立" },
        ["Controls"] = new[] { "Controls", "Controla", "Controla", "Contrôle", "Steuert", "Управляет", "يتحكم في", "שולט ב", "控制", "控制" },
        ["NEW"] = new[] { "NEW", "NUEVO", "NOVO", "NOUVEAU", "NEU", "НОВОЕ", "جديد", "חדש", "新", "新" },
        ["LightsInRoom"] = new[] { "Lights in this room", "Luces de esta habitación", "Luzes nesta divisão", "Lumières de cette pièce", "Lampen in diesem Raum", "Лампы в этой комнате", "الأضواء في هذه الغرفة", "האורות בחדר זה", "此房间中的灯", "此房間中的燈" },
        ["ApplyLights"] = new[] { "Apply lights", "Aplicar luces", "Aplicar luzes", "Appliquer les lumières", "Lampen übernehmen", "Применить лампы", "تطبيق الأضواء", "החלת אורות", "应用灯光", "套用燈光" },
        ["Group"] = new[] { "Group:", "Agrupar:", "Agrupar:", "Grouper :", "Gruppieren:", "Группировка:", "تجميع:", "קיבוץ:", "分组：", "分組：" },
        ["Working"] = new[] { "Working…", "Procesando…", "A processar…", "Traitement…", "Wird ausgeführt…", "Выполняется…", "جارٍ العمل…", "מעבד…", "处理中…", "處理中…" },
        ["In"] = new[] { "in", "en", "em", "dans", "in", "в", "في", "ב", "在", "在" },
        ["Section_Devices"] = new[] { "Devices", "Dispositivos", "Dispositivos", "Appareils", "Geräte", "Устройства", "الأجهزة", "מכשירים", "设备", "裝置" },
        ["Devices_Desc"] = new[] { "Add any Hue device (lights, plugs, sensors, switches), rename or remove.", "Añade cualquier dispositivo Hue (luces, enchufes, sensores, interruptores), renómbralo o quítalo.", "Adicione qualquer dispositivo Hue (luzes, tomadas, sensores, interruptores), renomeie ou remova.", "Ajoutez n'importe quel appareil Hue (lumières, prises, capteurs, interrupteurs), renommez ou supprimez.", "Beliebiges Hue-Gerät hinzufügen (Lampen, Steckdosen, Sensoren, Schalter), umbenennen oder entfernen.", "Добавьте любое устройство Hue (лампы, розетки, датчики, выключатели), переименуйте или удалите.", "أضف أي جهاز Hue (أضواء، مقابس، مستشعرات، مفاتيح)، أعد التسمية أو الإزالة.", "הוסף כל מכשיר Hue (אורות, שקעים, חיישנים, מתגים), שנה שם או הסר.", "添加任何 Hue 设备（灯、插座、传感器、开关），重命名或移除。", "新增任何 Hue 裝置（燈、插座、感應器、開關），重新命名或移除。" },
        ["SearchNewDevices"] = new[] { "Search for new devices", "Buscar nuevos dispositivos", "Procurar novos dispositivos", "Rechercher de nouveaux appareils", "Nach neuen Geräten suchen", "Искать новые устройства", "البحث عن أجهزة جديدة", "חיפוש מכשירים חדשים", "搜索新设备", "搜尋新裝置" },
        ["Section_Accessories"] = new[] { "Accessories", "Accesorios", "Acessórios", "Accessoires", "Zubehör", "Аксессуары", "الملحقات", "אביזרים", "配件", "配件" },
        ["Accessories_Desc"] = new[] { "Switches, motion sensors and buttons — rename, check battery, remove.", "Interruptores, sensores de movimiento y botones: renombra, revisa la batería, quita.", "Interruptores, sensores de movimento e botões — renomear, ver bateria, remover.", "Interrupteurs, capteurs de mouvement et boutons — renommer, vérifier la batterie, supprimer.", "Schalter, Bewegungsmelder und Tasten — umbenennen, Batterie prüfen, entfernen.", "Выключатели, датчики движения и кнопки — переименование, заряд, удаление.", "المفاتيح ومستشعرات الحركة والأزرار — إعادة التسمية، فحص البطارية، الإزالة.", "מתגים, חיישני תנועה ולחצנים — שינוי שם, בדיקת סוללה, הסרה.", "开关、运动传感器和按钮 — 重命名、查看电量、移除。", "開關、動作感應器和按鈕 — 重新命名、查看電量、移除。" },
        ["Section_Scenes"] = new[] { "Scenes", "Escenas", "Cenas", "Scènes", "Szenen", "Сцены", "المشاهد", "סצנות", "场景", "場景" },
        ["Scenes_Desc"] = new[] { "Add a built-in Hue scene to a room, or delete scenes.", "Añade una escena Hue integrada a una habitación o elimina escenas.", "Adicione uma cena Hue incorporada a uma divisão ou elimine cenas.", "Ajoutez une scène Hue intégrée à une pièce, ou supprimez des scènes.", "Eine integrierte Hue-Szene zu einem Raum hinzufügen oder Szenen löschen.", "Добавьте встроенную сцену Hue в комнату или удалите сцены.", "أضف مشهد Hue مدمجًا إلى غرفة، أو احذف المشاهد.", "הוסף סצנת Hue מובנית לחדר, או מחק סצנות.", "向房间添加内置 Hue 场景，或删除场景。", "為房間新增內建 Hue 場景，或刪除場景。" },
        ["AddSceneBtn"] = new[] { "Add scene", "Añadir escena", "Adicionar cena", "Ajouter une scène", "Szene hinzufügen", "Добавить сцену", "إضافة مشهد", "הוספת סצנה", "添加场景", "新增場景" },
        ["Section_Rooms"] = new[] { "Rooms & Zones", "Habitaciones y zonas", "Divisões e zonas", "Pièces et zones", "Räume & Zonen", "Комнаты и зоны", "الغرف والمناطق", "חדרים ואזורים", "房间和区域", "房間與區域" },
        ["Rooms_Desc"] = new[] { "Create rooms or zones, rename, delete, and choose which lights belong.", "Crea habitaciones o zonas, renómbralas, elimínalas y elige qué luces pertenecen.", "Crie divisões ou zonas, renomeie, elimine e escolha as luzes que pertencem.", "Créez des pièces ou des zones, renommez, supprimez et choisissez les lumières.", "Räume oder Zonen erstellen, umbenennen, löschen und Lampen zuordnen.", "Создавайте комнаты и зоны, переименовывайте, удаляйте и выбирайте лампы.", "أنشئ غرفًا أو مناطق، أعد التسمية، احذف، واختر الأضواء التي تنتمي إليها.", "צור חדרים או אזורים, שנה שם, מחק ובחר אילו אורות שייכים.", "创建房间或区域，重命名、删除，并选择包含哪些灯。", "建立房間或區域，重新命名、刪除，並選擇包含哪些燈。" },

        // ── Group modes / room types ────────────────────────────────────────
        ["Group_ByRoom"] = new[] { "By room", "Por habitación", "Por divisão", "Par pièce", "Nach Raum", "По комнате", "حسب الغرفة", "לפי חדר", "按房间", "依房間" },
        ["Group_ByType"] = new[] { "By type", "Por tipo", "Por tipo", "Par type", "Nach Typ", "По типу", "حسب النوع", "לפי סוג", "按类型", "依類型" },
        ["Group_Flat"] = new[] { "Flat", "Lista", "Lista", "Liste", "Liste", "Списком", "قائمة", "רשימה", "列表", "清單" },
        ["RoomType_Room"] = new[] { "Room", "Habitación", "Divisão", "Pièce", "Raum", "Комната", "غرفة", "חדר", "房间", "房間" },
        ["RoomType_Zone"] = new[] { "Zone", "Zona", "Zona", "Zone", "Zone", "Зона", "منطقة", "אזור", "区域", "區域" },

        // ── Synthetic groups / labels ───────────────────────────────────────
        ["All"] = new[] { "All", "Todo", "Tudo", "Tout", "Alle", "Все", "الكل", "הכול", "全部", "全部" },
        ["EveryRoom"] = new[] { "Every room", "Todas las habitaciones", "Todas as divisões", "Toutes les pièces", "Alle Räume", "Все комнаты", "كل الغرف", "כל החדרים", "所有房间", "所有房間" },
        ["Kind_Light"] = new[] { "Light", "Luz", "Luz", "Lumière", "Lampe", "Лампа", "ضوء", "אור", "灯", "燈" },
        ["Kind_Accessory"] = new[] { "Accessory", "Accesorio", "Acessório", "Accessoire", "Zubehör", "Аксессуар", "ملحق", "אביזר", "配件", "配件" },
        ["Type_Lights"] = new[] { "Lights", "Luces", "Luzes", "Lumières", "Lampen", "Лампы", "الأضواء", "אורות", "灯", "燈" },
        ["Unassigned"] = new[] { "Unassigned", "Sin asignar", "Não atribuído", "Non attribué", "Nicht zugewiesen", "Не назначено", "غير معيّن", "לא משויך", "未分配", "未指派" },
        ["Unreachable"] = new[] { "unreachable", "no disponible", "inacessível", "injoignable", "nicht erreichbar", "недоступно", "غير متصل", "לא זמין", "无法连接", "無法連線" },
        ["Never"] = new[] { "never", "nunca", "nunca", "jamais", "nie", "никогда", "أبدًا", "אף פעם", "从不", "從未" },
        ["NoBattery"] = new[] { "No battery", "Sin batería", "Sem bateria", "Pas de batterie", "Keine Batterie", "Нет батареи", "بدون بطارية", "אין סוללה", "无电池", "無電池" },
        ["Battery_Fmt"] = new[] { "Battery {0}%", "Batería {0}%", "Bateria {0}%", "Batterie {0}%", "Batterie {0}%", "Батарея {0}%", "البطارية {0}%", "סוללה {0}%", "电量 {0}%", "電量 {0}%" },
        ["NLights_Fmt"] = new[] { "{0} lights", "{0} luces", "{0} luzes", "{0} lumières", "{0} Lampen", "{0} ламп", "{0} أضواء", "{0} אורות", "{0} 个灯", "{0} 個燈" },
        ["NOffline_Fmt"] = new[] { "{0} offline", "{0} sin conexión", "{0} offline", "{0} hors ligne", "{0} offline", "не в сети: {0}", "{0} غير متصل", "{0} לא מחוברים", "{0} 个离线", "{0} 個離線" },
        ["Offline_NoPower"] = new[] { "Offline — no power or out of range", "Sin conexión: sin corriente o fuera de alcance", "Offline — sem energia ou fora de alcance", "Hors ligne — pas d'alimentation ou hors de portée", "Offline — kein Strom oder außer Reichweite", "Не в сети — нет питания или вне зоны", "غير متصل — لا توجد طاقة أو خارج النطاق", "לא מחובר — אין חשמל או מחוץ לטווח", "离线 — 未通电或超出范围", "離線 — 未通電或超出範圍" },
        ["LastSeen_Fmt"] = new[] { "last seen {0}", "visto {0}", "visto {0}", "vu {0}", "zuletzt {0}", "активность {0}", "آخر ظهور {0}", "נראה לאחרונה {0}", "最后活动 {0}", "最後活動 {0}" },
        ["Custom"] = new[] { "Custom", "Personalizada", "Personalizada", "Personnalisée", "Benutzerdefiniert", "Своя", "مخصص", "מותאם אישית", "自定义", "自訂" },

        // ── Main status / dialogs ───────────────────────────────────────────
        ["Status_AddBridgeToStart"] = new[] { "Add a bridge to get started.", "Añade un puente para empezar.", "Adicione uma ponte para começar.", "Ajoutez un pont pour commencer.", "Fügen Sie eine Bridge hinzu, um zu beginnen.", "Добавьте мост, чтобы начать.", "أضف جسرًا للبدء.", "הוסף גשר כדי להתחיל.", "添加网桥以开始。", "新增橋接器以開始。" },
        ["Status_NoBridgeSelected"] = new[] { "No bridge selected.", "Ningún puente seleccionado.", "Nenhuma ponte selecionada.", "Aucun pont sélectionné.", "Keine Bridge ausgewählt.", "Мост не выбран.", "لم يتم تحديد جسر.", "לא נבחר גשר.", "未选择网桥。", "未選擇橋接器。" },
        ["Status_LoadingBridge_Fmt"] = new[] { "Loading {0} ({1})…", "Cargando {0} ({1})…", "A carregar {0} ({1})…", "Chargement de {0} ({1})…", "{0} ({1}) wird geladen…", "Загрузка {0} ({1})…", "جارٍ تحميل {0} ({1})…", "טוען את {0} ({1})…", "正在加载 {0}（{1}）…", "正在載入 {0}（{1}）…" },
        ["Status_BridgeSummary_Fmt"] = new[] { "{0}: {1} lights, {2} rooms, {3} scenes.", "{0}: {1} luces, {2} habitaciones, {3} escenas.", "{0}: {1} luzes, {2} divisões, {3} cenas.", "{0} : {1} lumières, {2} pièces, {3} scènes.", "{0}: {1} Lampen, {2} Räume, {3} Szenen.", "{0}: ламп — {1}, комнат — {2}, сцен — {3}.", "{0}: {1} أضواء، {2} غرف، {3} مشاهد.", "{0}: {1} אורות, {2} חדרים, {3} סצנות.", "{0}：{1} 个灯，{2} 个房间，{3} 个场景。", "{0}：{1} 個燈，{2} 個房間，{3} 個場景。" },
        ["Status_FailedLoad_Fmt"] = new[] { "Failed to load bridge: {0}", "No se pudo cargar el puente: {0}", "Falha ao carregar a ponte: {0}", "Échec du chargement du pont : {0}", "Bridge konnte nicht geladen werden: {0}", "Не удалось загрузить мост: {0}", "فشل تحميل الجسر: {0}", "טעינת הגשר נכשלה: {0}", "加载网桥失败：{0}", "載入橋接器失敗：{0}" },
        ["Status_Error_Fmt"] = new[] { "Error: {0}", "Error: {0}", "Erro: {0}", "Erreur : {0}", "Fehler: {0}", "Ошибка: {0}", "خطأ: {0}", "שגיאה: {0}", "错误：{0}", "錯誤：{0}" },
        ["Confirm_DeleteHome_Fmt"] = new[] { "Delete home \"{0}\" and its {1} bridge(s) from the app?\nThe bridges stay paired on your network.", "¿Eliminar el hogar «{0}» y sus {1} puente(s) de la app?\nLos puentes siguen vinculados en tu red.", "Eliminar a casa «{0}» e as suas {1} ponte(s) da app?\nAs pontes continuam emparelhadas na sua rede.", "Supprimer la maison « {0} » et ses {1} pont(s) de l'app ?\nLes ponts restent associés sur votre réseau.", "Zuhause „{0}“ und seine {1} Bridge(s) aus der App entfernen?\nDie Bridges bleiben in Ihrem Netzwerk gekoppelt.", "Удалить дом «{0}» и его мосты ({1}) из приложения?\nМосты останутся связанными в вашей сети.", "حذف المنزل «{0}» و{1} جسر (جسور) من التطبيق؟\nتبقى الجسور مقترنة على شبكتك.", "למחוק את הבית «{0}» ואת {1} הגשרים שלו מהאפליקציה?\nהגשרים יישארו מותאמים ברשת שלך.", "从应用中删除住宅“{0}”及其 {1} 个网桥？\n网桥仍会在您的网络中保持配对。", "從應用程式中刪除住家「{0}」及其 {1} 個橋接器？\n橋接器仍會在您的網路中保持配對。" },
        ["Ask_AddHome"] = new[] { "Add home", "Añadir hogar", "Adicionar casa", "Ajouter une maison", "Zuhause hinzufügen", "Добавить дом", "إضافة منزل", "הוספת בית", "添加住宅", "新增住家" },
        ["Ask_RenameHome"] = new[] { "Rename home", "Renombrar hogar", "Renomear casa", "Renommer la maison", "Zuhause umbenennen", "Переименовать дом", "إعادة تسمية المنزل", "שינוי שם הבית", "重命名住宅", "重新命名住家" },
        ["Status_HomeExists_Fmt"] = new[] { "A home named \"{0}\" already exists.", "Ya existe un hogar llamado «{0}».", "Já existe uma casa chamada «{0}».", "Une maison nommée « {0} » existe déjà.", "Ein Zuhause namens „{0}“ existiert bereits.", "Дом с именем «{0}» уже существует.", "يوجد بالفعل منزل باسم «{0}».", "כבר קיים בית בשם «{0}».", "已存在名为“{0}”的住宅。", "已存在名為「{0}」的住家。" },
        ["Ask_Name"] = new[] { "Name", "Nombre", "Nome", "Nom", "Name", "Имя", "الاسم", "שם", "名称", "名稱" },
        ["Dialog_Confirm"] = new[] { "Confirm", "Confirmar", "Confirmar", "Confirmer", "Bestätigen", "Подтверждение", "تأكيد", "אישור", "确认", "確認" },
        ["Msg_AddSelectBridgeFirst"] = new[] { "Add and select a bridge first.", "Primero añade y selecciona un puente.", "Primeiro adicione e selecione uma ponte.", "Ajoutez et sélectionnez d'abord un pont.", "Fügen Sie zuerst eine Bridge hinzu und wählen Sie sie aus.", "Сначала добавьте и выберите мост.", "أضف وحدد جسرًا أولًا.", "הוסף ובחר גשר תחילה.", "请先添加并选择一个网桥。", "請先新增並選擇一個橋接器。" },
        ["Confirm_DeleteScene_Fmt"] = new[] { "Delete scene \"{0}\"?", "¿Eliminar la escena «{0}»?", "Eliminar a cena «{0}»?", "Supprimer la scène « {0} » ?", "Szene „{0}“ löschen?", "Удалить сцену «{0}»?", "حذف المشهد «{0}»؟", "למחוק את הסצנה «{0}»?", "删除场景“{0}”？", "刪除場景「{0}」？" },
        ["Status_AddedScene_Fmt"] = new[] { "Added \"{0}\" to {1}.", "Se añadió «{0}» a {1}.", "«{0}» adicionada a {1}.", "« {0} » ajoutée à {1}.", "„{0}“ zu {1} hinzugefügt.", "«{0}» добавлена в {1}.", "تمت إضافة «{0}» إلى {1}.", "«{0}» נוספה אל {1}.", "已将“{0}”添加到 {1}。", "已將「{0}」新增至 {1}。" },
        ["Status_DeletedScene_Fmt"] = new[] { "Deleted scene \"{0}\".", "Escena «{0}» eliminada.", "Cena «{0}» eliminada.", "Scène « {0} » supprimée.", "Szene „{0}“ gelöscht.", "Сцена «{0}» удалена.", "تم حذف المشهد «{0}».", "הסצנה «{0}» נמחקה.", "已删除场景“{0}”。", "已刪除場景「{0}」。" },
        ["ThisBridge"] = new[] { "this bridge", "este puente", "esta ponte", "ce pont", "diese Bridge", "этот мост", "هذا الجسر", "גשר זה", "此网桥", "此橋接器" },

        // ── Add-bridge view model ───────────────────────────────────────────
        ["Status_DiscoverHint"] = new[] { "Discover bridges, or type an IP address, then press Pair.", "Descubre puentes o escribe una IP y pulsa Vincular.", "Descubra pontes ou escreva um IP e prima Emparelhar.", "Découvrez des ponts ou saisissez une IP, puis Associer.", "Bridges suchen oder eine IP eingeben, dann Koppeln.", "Найдите мосты или введите IP, затем нажмите «Связать».", "اكتشف الجسور، أو أدخل عنوان IP، ثم اضغط إقران.", "גלה גשרים, או הקלד כתובת IP, ואז לחץ על התאמה.", "发现网桥，或输入 IP 地址，然后按配对。", "探索橋接器，或輸入 IP 位址，然後按配對。" },
        ["Status_Searching"] = new[] { "Searching the network for bridges…", "Buscando puentes en la red…", "A procurar pontes na rede…", "Recherche de ponts sur le réseau…", "Netzwerk wird nach Bridges durchsucht…", "Поиск мостов в сети…", "جارٍ البحث في الشبكة عن جسور…", "מחפש גשרים ברשת…", "正在网络中搜索网桥…", "正在網路中搜尋橋接器…" },
        ["Status_FoundBridges_Fmt"] = new[] { "Found {0} bridge(s). Select one or enter an IP, then Pair.", "Se encontraron {0} puente(s). Elige uno o escribe una IP y Vincular.", "{0} ponte(s) encontrada(s). Escolha uma ou introduza um IP e Emparelhar.", "{0} pont(s) trouvé(s). Choisissez-en un ou saisissez une IP, puis Associer.", "{0} Bridge(s) gefunden. Wählen oder IP eingeben, dann Koppeln.", "Найдено мостов: {0}. Выберите один или введите IP, затем «Связать».", "تم العثور على {0} جسر (جسور). حدد واحدًا أو أدخل عنوان IP، ثم إقران.", "נמצאו {0} גשרים. בחר אחד או הזן כתובת IP, ואז התאמה.", "找到 {0} 个网桥。选择一个或输入 IP，然后配对。", "找到 {0} 個橋接器。選擇一個或輸入 IP，然後配對。" },
        ["Status_NoneFound"] = new[] { "No bridges found automatically. Enter the bridge IP manually.", "No se encontraron puentes automáticamente. Escribe la IP manualmente.", "Nenhuma ponte encontrada automaticamente. Introduza o IP manualmente.", "Aucun pont trouvé automatiquement. Saisissez l'IP manuellement.", "Keine Bridges automatisch gefunden. IP manuell eingeben.", "Мосты не найдены автоматически. Введите IP вручную.", "لم يتم العثور على جسور تلقائيًا. أدخل عنوان IP للجسر يدويًا.", "לא נמצאו גשרים אוטומטית. הזן את כתובת ה-IP של הגשר ידנית.", "未自动找到网桥。请手动输入网桥 IP。", "未自動找到橋接器。請手動輸入橋接器 IP。" },
        ["Status_EnterIpFirst"] = new[] { "Enter a bridge IP address first.", "Primero escribe la IP del puente.", "Introduza primeiro o IP da ponte.", "Saisissez d'abord l'IP du pont.", "Geben Sie zuerst die IP der Bridge ein.", "Сначала введите IP-адрес моста.", "أدخل عنوان IP للجسر أولًا.", "הזן תחילה כתובת IP של גשר.", "请先输入网桥 IP 地址。", "請先輸入橋接器 IP 位址。" },
        ["Status_Pairing_Fmt"] = new[] { "Pairing with {0} — press the link button on the bridge now…", "Vinculando con {0}: pulsa el botón del puente ahora…", "A emparelhar com {0} — prima agora o botão na ponte…", "Association avec {0} — appuyez sur le bouton du pont maintenant…", "Kopplung mit {0} — jetzt die Link-Taste an der Bridge drücken…", "Связывание с {0} — нажмите кнопку на мосту сейчас…", "جارٍ الإقران مع {0} — اضغط زر الربط على الجسر الآن…", "מתאים עם {0} — לחץ עכשיו על לחצן הקישור בגשר…", "正在与 {0} 配对 — 现在请按下网桥上的连接按钮…", "正在與 {0} 配對 — 現在請按下橋接器上的連結按鈕…" },
        ["Status_Paired_Fmt"] = new[] { "Paired with {0}.", "Vinculado con {0}.", "Emparelhado com {0}.", "Associé à {0}.", "Mit {0} gekoppelt.", "Связано с {0}.", "تم الإقران مع {0}.", "בוצעה התאמה עם {0}.", "已与 {0} 配对。", "已與 {0} 配對。" },
        ["Status_LinkNotDetected"] = new[] { "Link button not detected. Press it on the bridge, then click Pair again.", "No se detectó el botón. Púlsalo en el puente y vuelve a Vincular.", "Botão não detetado. Prima-o na ponte e clique em Emparelhar novamente.", "Bouton non détecté. Appuyez sur le pont, puis réessayez Associer.", "Link-Taste nicht erkannt. An der Bridge drücken und erneut Koppeln.", "Кнопка не обнаружена. Нажмите её на мосту и снова «Связать».", "لم يتم اكتشاف زر الربط. اضغطه على الجسر، ثم انقر إقران مرة أخرى.", "לחצן הקישור לא זוהה. לחץ עליו בגשר, ואז לחץ שוב על התאמה.", "未检测到连接按钮。请在网桥上按下它，然后再次点击配对。", "未偵測到連結按鈕。請在橋接器上按下它，然後再次點選配對。" },
        ["Status_PairingFailed_Fmt"] = new[] { "Pairing failed: {0}", "Error al vincular: {0}", "Falha no emparelhamento: {0}", "Échec de l'association : {0}", "Kopplung fehlgeschlagen: {0}", "Ошибка связывания: {0}", "فشل الإقران: {0}", "ההתאמה נכשלה: {0}", "配对失败：{0}", "配對失敗：{0}" },

        // ── Devices section ─────────────────────────────────────────────────
        ["Status_LoadingDevices"] = new[] { "Loading devices…", "Cargando dispositivos…", "A carregar dispositivos…", "Chargement des appareils…", "Geräte werden geladen…", "Загрузка устройств…", "جارٍ تحميل الأجهزة…", "טוען מכשירים…", "正在加载设备…", "正在載入裝置…" },
        ["Status_DeviceSummary_Fmt"] = new[] { "{0} lights, {1} accessories.", "{0} luces, {1} accesorios.", "{0} luzes, {1} acessórios.", "{0} lumières, {1} accessoires.", "{0} Lampen, {1} Zubehör.", "Ламп — {0}, аксессуаров — {1}.", "{0} أضواء، {1} ملحقات.", "{0} אורות, {1} אביזרים.", "{0} 个灯，{1} 个配件。", "{0} 個燈，{1} 個配件。" },
        ["Status_SearchingNew"] = new[] { "Searching for new devices… (put accessories in pairing mode)", "Buscando nuevos dispositivos… (pon los accesorios en modo vinculación)", "A procurar novos dispositivos… (coloque os acessórios em modo de emparelhamento)", "Recherche de nouveaux appareils… (mettez les accessoires en mode association)", "Suche nach neuen Geräten… (Zubehör in den Kopplungsmodus versetzen)", "Поиск новых устройств… (переведите аксессуары в режим связывания)", "جارٍ البحث عن أجهزة جديدة… (ضع الملحقات في وضع الإقران)", "מחפש מכשירים חדשים… (העבר את האביזרים למצב התאמה)", "正在搜索新设备…（将配件置于配对模式）", "正在搜尋新裝置…（將配件置於配對模式）" },
        ["Status_SearchingFound_Fmt"] = new[] { "Searching… found {0} so far", "Buscando… {0} encontrados", "A procurar… {0} encontrado(s)", "Recherche… {0} trouvé(s)", "Suche… bisher {0} gefunden", "Поиск… найдено: {0}", "جارٍ البحث… تم العثور على {0} حتى الآن", "מחפש… נמצאו {0} עד כה", "正在搜索…目前找到 {0} 个", "正在搜尋…目前找到 {0} 個" },
        ["Status_FoundNew_Fmt"] = new[] { "Found {0} new device(s) — highlighted below.", "Se encontraron {0} dispositivo(s) nuevo(s), resaltados abajo.", "{0} novo(s) dispositivo(s) encontrado(s) — realçados abaixo.", "{0} nouvel(s) appareil(s) trouvé(s) — surlignés ci-dessous.", "{0} neue(s) Gerät(e) gefunden — unten hervorgehoben.", "Найдено новых устройств: {0} — отмечены ниже.", "تم العثور على {0} جهاز (أجهزة) جديدة — مميّزة أدناه.", "נמצאו {0} מכשירים חדשים — מודגשים למטה.", "找到 {0} 个新设备 — 已在下方高亮。", "找到 {0} 個新裝置 — 已在下方標示。" },
        ["Status_NoNew"] = new[] { "No new devices found. For accessories, press their pairing button and search again.", "No se encontraron dispositivos nuevos. Para accesorios, pulsa su botón de vinculación y busca de nuevo.", "Nenhum dispositivo novo. Para acessórios, prima o botão de emparelhamento e procure novamente.", "Aucun nouvel appareil. Pour les accessoires, appuyez sur leur bouton et relancez la recherche.", "Keine neuen Geräte gefunden. Bei Zubehör die Kopplungstaste drücken und erneut suchen.", "Новые устройства не найдены. Для аксессуаров нажмите кнопку связывания и повторите поиск.", "لم يتم العثور على أجهزة جديدة. للملحقات، اضغط زر الإقران وابحث مرة أخرى.", "לא נמצאו מכשירים חדשים. עבור אביזרים, לחץ על לחצן ההתאמה שלהם וחפש שוב.", "未找到新设备。对于配件，请按下其配对按钮并重新搜索。", "未找到新裝置。對於配件，請按下其配對按鈕並重新搜尋。" },
        ["Confirm_DeleteDevice_Fmt"] = new[] { "Delete \"{0}\" from the bridge?\nThe device will be unpaired and removed.", "¿Eliminar «{0}» del puente?\nEl dispositivo se desvinculará y se quitará.", "Eliminar «{0}» da ponte?\nO dispositivo será desemparelhado e removido.", "Supprimer « {0} » du pont ?\nL'appareil sera dissocié et retiré.", "„{0}“ von der Bridge entfernen?\nDas Gerät wird entkoppelt und entfernt.", "Удалить «{0}» с моста?\nУстройство будет отвязано и удалено.", "حذف «{0}» من الجسر؟\nسيتم إلغاء إقران الجهاز وإزالته.", "למחוק את «{0}» מהגשר?\nהמכשיר ינותק ויוסר.", "从网桥删除“{0}”？\n该设备将被取消配对并移除。", "從橋接器刪除「{0}」？\n該裝置將被取消配對並移除。" },
        ["Status_Deleted_Fmt"] = new[] { "Deleted \"{0}\".", "«{0}» eliminado.", "«{0}» eliminado.", "« {0} » supprimé.", "„{0}“ gelöscht.", "«{0}» удалено.", "تم حذف «{0}».", "«{0}» נמחק.", "已删除“{0}”。", "已刪除「{0}」。" },

        // ── Accessories section ─────────────────────────────────────────────
        ["Status_LoadingAccessories"] = new[] { "Loading accessories…", "Cargando accesorios…", "A carregar acessórios…", "Chargement des accessoires…", "Zubehör wird geladen…", "Загрузка аксессуаров…", "جارٍ تحميل الملحقات…", "טוען אביזרים…", "正在加载配件…", "正在載入配件…" },
        ["Status_AccessorySummary_Fmt"] = new[] { "{0} accessories.", "{0} accesorios.", "{0} acessórios.", "{0} accessoires.", "{0} Zubehörteile.", "Аксессуаров: {0}.", "{0} ملحقات.", "{0} אביזרים.", "{0} 个配件。", "{0} 個配件。" },
        ["Confirm_SetSwitch_Fmt"] = new[] { "Set \"{0}\" to control {1}?\nThis replaces the switch's current button rules. ON activates {1}'s first scene.", "¿Configurar «{0}» para controlar {1}?\nEsto reemplaza las reglas actuales del interruptor. ON activa la primera escena de {1}.", "Definir «{0}» para controlar {1}?\nIsto substitui as regras atuais dos botões. LIGAR ativa a primeira cena de {1}.", "Configurer « {0} » pour contrôler {1} ?\nCela remplace les règles actuelles de l'interrupteur. ON active la première scène de {1}.", "„{0}“ so einstellen, dass es {1} steuert?\nDies ersetzt die aktuellen Tastenregeln. EIN aktiviert die erste Szene von {1}.", "Настроить «{0}» для управления {1}?\nЭто заменит текущие правила кнопок. «Вкл» активирует первую сцену {1}.", "تعيين «{0}» للتحكم في {1}؟\nيستبدل هذا قواعد أزرار المفتاح الحالية. التشغيل يفعّل أول مشهد لـ {1}.", "להגדיר את «{0}» לשלוט ב-{1}?\nזה מחליף את כללי הלחצנים הנוכחיים של המתג. הפעלה מפעילה את הסצנה הראשונה של {1}.", "将“{0}”设置为控制 {1}？\n这将替换开关当前的按钮规则。开启会激活 {1} 的第一个场景。", "將「{0}」設定為控制 {1}？\n這將取代開關目前的按鈕規則。開啟會啟動 {1} 的第一個場景。" },
        ["Status_Programming_Fmt"] = new[] { "Programming \"{0}\"…", "Programando «{0}»…", "A programar «{0}»…", "Programmation de « {0} »…", "„{0}“ wird programmiert…", "Программирование «{0}»…", "جارٍ برمجة «{0}»…", "מתכנת את «{0}»…", "正在编程“{0}”…", "正在設定「{0}」…" },
        ["Status_SwitchSet_Fmt"] = new[] { "\"{0}\" now controls {1} (ON = its first scene).", "«{0}» ahora controla {1} (ON = su primera escena).", "«{0}» agora controla {1} (LIGAR = a primeira cena).", "« {0} » contrôle désormais {1} (ON = sa première scène).", "„{0}“ steuert jetzt {1} (EIN = erste Szene).", "«{0}» теперь управляет {1} (Вкл = первая сцена).", "«{0}» يتحكم الآن في {1} (التشغيل = أول مشهد له).", "«{0}» שולט כעת ב-{1} (הפעלה = הסצנה הראשונה שלו).", "“{0}”现在控制 {1}（开启 = 其第一个场景）。", "「{0}」現在控制 {1}（開啟 = 其第一個場景）。" },
        ["Confirm_DeleteAccessory_Fmt"] = new[] { "Delete \"{0}\" from the bridge?\nThe accessory will be unpaired.", "¿Eliminar «{0}» del puente?\nEl accesorio se desvinculará.", "Eliminar «{0}» da ponte?\nO acessório será desemparelhado.", "Supprimer « {0} » du pont ?\nL'accessoire sera dissocié.", "„{0}“ von der Bridge entfernen?\nDas Zubehör wird entkoppelt.", "Удалить «{0}» с моста?\nАксессуар будет отвязан.", "حذف «{0}» من الجسر؟\nسيتم إلغاء إقران الملحق.", "למחוק את «{0}» מהגשר?\nהאביזר ינותק.", "从网桥删除“{0}”？\n该配件将被取消配对。", "從橋接器刪除「{0}」？\n該配件將被取消配對。" },

        // ── Rooms section ───────────────────────────────────────────────────
        ["Status_LoadingRooms"] = new[] { "Loading rooms…", "Cargando habitaciones…", "A carregar divisões…", "Chargement des pièces…", "Räume werden geladen…", "Загрузка комнат…", "جارٍ تحميل الغرف…", "טוען חדרים…", "正在加载房间…", "正在載入房間…" },
        ["Status_RoomsSummary_Fmt"] = new[] { "{0} rooms & zones.", "{0} habitaciones y zonas.", "{0} divisões e zonas.", "{0} pièces et zones.", "{0} Räume & Zonen.", "Комнат и зон: {0}.", "{0} غرف ومناطق.", "{0} חדרים ואזורים.", "{0} 个房间和区域。", "{0} 個房間與區域。" },
        ["Status_EnterName"] = new[] { "Enter a name.", "Escribe un nombre.", "Introduza um nome.", "Saisissez un nom.", "Geben Sie einen Namen ein.", "Введите название.", "أدخل اسمًا.", "הזן שם.", "请输入名称。", "請輸入名稱。" },
        ["Status_CreatedRoom_Fmt"] = new[] { "Created {0} \"{1}\". Tick lights and Apply.", "Se creó {0} «{1}». Marca luces y Aplica.", "{0} «{1}» criada. Marque as luzes e Aplicar.", "{0} « {1} » créée. Cochez les lumières et Appliquer.", "{0} „{1}“ erstellt. Lampen anhaken und Übernehmen.", "Создано: {0} «{1}». Отметьте лампы и примените.", "تم إنشاء {0} «{1}». حدد الأضواء واضغط تطبيق.", "נוצר {0} «{1}». סמן אורות ולחץ החל.", "已创建{0}“{1}”。勾选灯并应用。", "已建立{0}「{1}」。勾選燈並套用。" },
        ["Confirm_DeleteRoom_Fmt"] = new[] { "Delete \"{0}\"?\nThe {1} is removed; its lights stay paired.", "¿Eliminar «{0}»?\nSe quita la {1}; sus luces siguen vinculadas.", "Eliminar «{0}»?\nA {1} é removida; as luzes continuam emparelhadas.", "Supprimer « {0} » ?\nLa {1} est retirée ; ses lumières restent associées.", "„{0}“ löschen?\n{1} wird entfernt; die Lampen bleiben gekoppelt.", "Удалить «{0}»?\n{1} будет удалена; лампы останутся связанными.", "حذف «{0}»؟\nتتم إزالة {1}؛ تبقى أضواؤها مقترنة.", "למחוק את «{0}»?\n{1} תוסר; האורות שלה יישארו מותאמים.", "删除“{0}”？\n将移除该{1}；其灯仍保持配对。", "刪除「{0}」？\n將移除該{1}；其燈仍保持配對。" },
        ["Status_AtLeastOneLight"] = new[] { "A room must keep at least one light.", "Una habitación debe tener al menos una luz.", "Uma divisão deve manter pelo menos uma luz.", "Une pièce doit garder au moins une lumière.", "Ein Raum muss mindestens eine Lampe behalten.", "В комнате должна остаться хотя бы одна лампа.", "يجب أن تحتفظ الغرفة بضوء واحد على الأقل.", "חדר חייב לשמור על אור אחד לפחות.", "房间必须至少保留一个灯。", "房間必須至少保留一個燈。" },
        ["Status_UpdatedLights_Fmt"] = new[] { "Updated lights in \"{0}\".", "Luces actualizadas en «{0}».", "Luzes atualizadas em «{0}».", "Lumières mises à jour dans « {0} ».", "Lampen in „{0}“ aktualisiert.", "Лампы в «{0}» обновлены.", "تم تحديث الأضواء في «{0}».", "האורות ב-«{0}» עודכנו.", "已更新“{0}”中的灯。", "已更新「{0}」中的燈。" },

        // ── Scenes section ──────────────────────────────────────────────────
        ["Status_LoadingScenes"] = new[] { "Loading scenes…", "Cargando escenas…", "A carregar cenas…", "Chargement des scènes…", "Szenen werden geladen…", "Загрузка сцен…", "جارٍ تحميل المشاهد…", "טוען סצנות…", "正在加载场景…", "正在載入場景…" },
        ["Status_ScenesSummary_Fmt"] = new[] { "{0} scenes.", "{0} escenas.", "{0} cenas.", "{0} scènes.", "{0} Szenen.", "Сцен: {0}.", "{0} مشاهد.", "{0} סצנות.", "{0} 个场景。", "{0} 個場景。" },
        ["Status_PickScene"] = new[] { "Pick a Hue scene.", "Elige una escena Hue.", "Escolha uma cena Hue.", "Choisissez une scène Hue.", "Wählen Sie eine Hue-Szene.", "Выберите сцену Hue.", "اختر مشهد Hue.", "בחר סצנת Hue.", "选择一个 Hue 场景。", "選擇一個 Hue 場景。" },
        ["Status_PickRoom"] = new[] { "Pick a room.", "Elige una habitación.", "Escolha uma divisão.", "Choisissez une pièce.", "Wählen Sie einen Raum.", "Выберите комнату.", "اختر غرفة.", "בחר חדר.", "选择一个房间。", "選擇一個房間。" },

        // ── Main section / offline indicator ────────────────────────────────
        ["Offline_Badge"] = new[] { "OFFLINE", "SIN CONEXIÓN", "OFFLINE", "HORS LIGNE", "OFFLINE", "НЕ В СЕТИ", "غير متصل", "לא מחובר", "离线", "離線" },
        ["Offline_Tooltip"] = new[] { "This light is offline. The bridge cannot reach it — usually the fixture's wall switch is off, the bulb was removed, or it is out of Zigbee range. Restore power and wait about a minute.", "Esta luz está sin conexión. El puente no puede alcanzarla: normalmente el interruptor de pared está apagado, se quitó la bombilla o está fuera del alcance Zigbee. Restablece la corriente y espera un minuto.", "Esta luz está offline. A ponte não a consegue alcançar — normalmente o interruptor de parede está desligado, a lâmpada foi removida ou está fora do alcance Zigbee. Reponha a energia e aguarde cerca de um minuto.", "Cette lumière est hors ligne. Le pont ne peut pas la joindre — généralement l'interrupteur mural est éteint, l'ampoule a été retirée ou elle est hors de portée Zigbee. Rétablissez l'alimentation et attendez environ une minute.", "Diese Lampe ist offline. Die Bridge erreicht sie nicht – meist ist der Wandschalter aus, das Leuchtmittel entfernt oder sie ist außerhalb der Zigbee-Reichweite. Strom wiederherstellen und etwa eine Minute warten.", "Лампа не в сети. Мост не может до неё достучаться — обычно выключен настенный выключатель, лампа выкручена или она вне зоны Zigbee. Включите питание и подождите около минуты.", "هذا الضوء غير متصل. لا يستطيع الجسر الوصول إليه — عادةً يكون مفتاح الحائط مطفأً أو أُزيل المصباح أو أنه خارج نطاق Zigbee. أعد التيار وانتظر نحو دقيقة.", "האור הזה לא מחובר. הגשר לא מצליח להגיע אליו — בדרך כלל מתג הקיר כבוי, הנורה הוסרה או שהיא מחוץ לטווח Zigbee. החזר את החשמל והמתן כדקה.", "此灯已离线。网桥无法连接到它——通常是墙壁开关已关闭、灯泡被拆下或超出 Zigbee 范围。恢复供电后等待约一分钟。", "此燈已離線。橋接器無法連線到它——通常是牆壁開關已關閉、燈泡被拆下或超出 Zigbee 範圍。恢復供電後等待約一分鐘。" },
        ["Section_Main"] = new[] { "Main", "General", "Geral", "Général", "Allgemein", "Основное", "عام", "כללי", "常规", "一般" },
        ["Main_Subtitle"] = new[] { "App-wide preferences that apply to every bridge.", "Preferencias generales que se aplican a todos los puentes.", "Preferências gerais que se aplicam a todas as pontes.", "Préférences générales qui s'appliquent à tous les ponts.", "App-weite Einstellungen, die für jede Bridge gelten.", "Общие настройки приложения для всех мостов.", "تفضيلات عامة تنطبق على كل الجسور.", "העדפות כלליות שחלות על כל הגשרים.", "适用于所有网桥的应用级首选项。", "適用於所有橋接器的應用程式偏好設定。" },
        ["AutoRefresh"] = new[] { "Auto-refresh", "Actualización automática", "Atualização automática", "Actualisation automatique", "Automatisch aktualisieren", "Автообновление", "تحديث تلقائي", "רענון אוטומטי", "自动刷新", "自動重新整理" },
        ["AutoRefresh_Desc"] = new[] { "Periodically checks the bridge so on/off and offline status stay current without pressing Refresh. Turn off to update only manually.", "Consulta el puente periódicamente para que el estado encendido/apagado y sin conexión esté al día sin pulsar Actualizar. Desactívalo para actualizar solo manualmente.", "Consulta a ponte periodicamente para manter o estado ligado/desligado e offline atualizado sem premir Atualizar. Desative para atualizar só manualmente.", "Interroge le pont régulièrement pour que l'état allumé/éteint et hors ligne reste à jour sans appuyer sur Actualiser. Désactivez pour ne mettre à jour que manuellement.", "Fragt die Bridge regelmäßig ab, damit Ein/Aus- und Offline-Status ohne Aktualisieren aktuell bleiben. Ausschalten, um nur manuell zu aktualisieren.", "Периодически опрашивает мост, чтобы состояние вкл/выкл и «не в сети» обновлялось без кнопки «Обновить». Выключите, чтобы обновлять только вручную.", "يتحقق من الجسر دوريًا لتبقى حالة التشغيل/الإيقاف وعدم الاتصال محدثة دون الضغط على تحديث. أوقفه للتحديث يدويًا فقط.", "בודק את הגשר מעת לעת כדי שמצב הפעלה/כיבוי וניתוק יתעדכן בלי ללחוץ על רענון. כבה כדי לעדכן רק ידנית.", "定期检查网桥，使开/关和离线状态无需点击刷新即可保持最新。关闭后仅手动更新。", "定期檢查橋接器，讓開/關與離線狀態無需點選重新整理即可保持最新。關閉後僅手動更新。" },
        ["AutoRefresh_Every_Fmt"] = new[] { "Check every {0} seconds", "Comprobar cada {0} segundos", "Verificar a cada {0} segundos", "Vérifier toutes les {0} secondes", "Alle {0} Sekunden prüfen", "Проверять каждые {0} с", "التحقق كل {0} ثانية", "בדיקה כל {0} שניות", "每 {0} 秒检查一次", "每 {0} 秒檢查一次" },
    };

    /// <summary>Returns the translation for <paramref name="key"/> in language index <paramref name="idx"/>, or the key itself if missing.</summary>
    internal static string Get(string key, int idx)
        => All.TryGetValue(key, out string[]? v) && idx >= 0 && idx < v.Length ? v[idx] : key;
}
